### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by marklawlor** [marklawlor/prisma-supabase#1]
Not a complete list, adding things as I go

- [ ] All filter operators
- [ ] Compound keys
- [ ] Where inside includes
- [ ] Distinct [(prisma does this in-memory)](https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing#distinct-under-the-hood)
